apiVersion: apps/v1
kind: Deployment
metadata:
  name: autodeploy77
  labels:
    app: autodeploy77
    kubernetes.azure.com/generator: devhub
  namespace: namespace-workflow-1716798359363
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autodeploy77
  template:
    metadata:
      labels:
        app: autodeploy77
    spec:
      containers:
        - name: autodeploy77
          image: acrworkflow1716798359363.azurecr.io/image-workflow-1716798359363:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
